---
title: "Frequentist analysis for supplement"
author: "Joern Alexander Quent"
date: "21/10/2021"
output: html_document
---

```{r setup, include=FALSE}
# Libraries
library(assortedRFunctions) # install via devtools::install_github("JAQuent/assortedRFunctions")
library(knitr)
library(ggplot2)
library(brms)
library(plyr)
library(lmerTest)
library(MRColour)
library(BayesFactor)
library(cowplot)
library(polspline)
library(gridExtra)
library(grid)

# Options
options(scipen=999)
opts_knit$set(eval.after = 'fig.cap')
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, include = TRUE)

######################################################
# Path to parent folder schemaVR
path2parent <- "D:/Alex/Laptop/Desktop/schemaVR" # This need to be changed to run this document
######################################################
```

# Pooled analysis
```{r pooled_3AFC}
# /*
# ----------------------------- Data --------------------------
# */
# Loading all .RData files
load("D:/Alex/Laptop/Desktop/schemaVR/schemaVR1/data/dataSchemaVR1_cleaned.RData")
load("D:/Alex/Laptop/Desktop/schemaVR/schemaVR2/data/dataSchemaVR2_cleaned.RData")
load("D:/Alex/Laptop/Desktop/schemaVR/schemaVR3/data/dataSchemaVR3_cleaned.RData")
load("D:/Alex/Laptop/Desktop/schemaVR/schemaVR4/data/dataSchemaVR4_cleaned.RData")

# Create AFC data for schemaVR4
dataSchemaVR4_AFC    <- subset(dataSchemaVR4, dataSchemaVR4$resCon != 0)

# Combine data to one data frame
combinedData_AFC <- data.frame(Experiment = c(rep('1', length(dataSchemaVR1_AFC$subNum)),
                                              rep('2', length(dataSchemaVR2_AFC$subNum)),
                                              rep('3a', length(dataSchemaVR3_AFC$subNum)),
                                              rep('3b', length(dataSchemaVR4_AFC$subNum))),
                               set        = c(rep('1', length(dataSchemaVR1_AFC$subNum)),
                                              rep('2', length(dataSchemaVR2_AFC$subNum)),
                                              as.character(dataSchemaVR3_AFC$setNum),
                                              as.character(dataSchemaVR4_AFC$setNum)),
                               subNum = c(as.character(dataSchemaVR1_AFC$subNum),
                                          as.character(dataSchemaVR2_AFC$subNum),
                                          as.character(dataSchemaVR3_AFC$subNum),
                                          as.character(dataSchemaVR4_AFC$subNum)),
                               objNum = c(dataSchemaVR1_AFC$objNum,
                                          dataSchemaVR2_AFC$objNum,
                                          dataSchemaVR3_AFC$objNum,
                                          dataSchemaVR4_AFC$objNum),
                               objLocTargetRating = c(dataSchemaVR1_AFC$objLocTargetRating,
                                                      dataSchemaVR2_AFC$objLocTargetRating,
                                                      dataSchemaVR3_AFC$objLocTargetRating,
                                                      dataSchemaVR4_AFC$objLocTargetRating),
                               accAFC = c(dataSchemaVR1_AFC$accAFC,
                                          dataSchemaVR2_AFC$accAFC,
                                          dataSchemaVR3_AFC$accAFC,
                                          dataSchemaVR4_AFC$accAFC))

combinedData_AFC$Exp    <- combinedData_AFC$objLocTargetRating 
combinedData_AFC$subNum <- as.character(combinedData_AFC$subNum)
combinedData_AFC$s_x <- (combinedData_AFC$Exp - mean(combinedData_AFC$Exp ))/(sd(combinedData_AFC$Exp)/0.5)
```

```{r pooled_3AFC_analysis}
pooled_3AFC <- glmer(accAFC ~  s_x + I(s_x*s_x) 
                     + (1 | subNum)
                     + (1 | objNum), 
                    data = combinedData_AFC, 
                    family = binomial, 
                    control = glmerControl(optimizer = "bobyqa"),
                    nAGQ = 1)

pooled_3AFC_tab <- createResultTable(pooled_3AFC)
```

```{r pooled_recall}
# Re creating recall DF because there was an error in the code
dataSchemaVR2_recall <- subset(dataSchemaVR2, dataSchemaVR2$recallMemory != 0 | is.na(dataSchemaVR2$recallMemory))
dataSchemaVR3_recall <- subset(dataSchemaVR3, dataSchemaVR3$recallMemory != 0 | is.na(dataSchemaVR3$recallMemory))
dataSchemaVR4_recall <- subset(dataSchemaVR4, dataSchemaVR4$recallMemory != 0 | is.na(dataSchemaVR4$recallMemory))

# Combine data to one data frame
combinedData_recall <- data.frame(Experiment = c(rep('1', length(dataSchemaVR1_recall$subNum)),
                                              rep('2', length(dataSchemaVR2_recall$subNum)),
                                              rep('3a', length(dataSchemaVR3_recall$subNum)),
                                              rep('3b', length(dataSchemaVR4_recall$subNum))),
                               set        = c(rep('1', length(dataSchemaVR1_recall$subNum)),
                                              rep('2', length(dataSchemaVR2_recall$subNum)),
                                              as.character(dataSchemaVR3_recall$setNum),
                                              as.character(dataSchemaVR4_recall$setNum)),
                               subNum = c(as.character(dataSchemaVR1_recall$subNum),
                                          as.character(dataSchemaVR2_recall$subNum),
                                          as.character(dataSchemaVR3_recall$subNum),
                                          as.character(dataSchemaVR4_recall$subNum)),
                               objNum = c(dataSchemaVR1_recall$objNum,
                                          dataSchemaVR2_recall$objNum,
                                          dataSchemaVR3_recall$objNum,
                                          dataSchemaVR4_recall$objNum),
                               objLocTargetRating = c(dataSchemaVR1_recall$objLocTargetRating,
                                                      dataSchemaVR2_recall$objLocTargetRating,
                                                      dataSchemaVR3_recall$objLocTargetRating,
                                                      dataSchemaVR4_recall$objLocTargetRating),
                               accRecall = c(dataSchemaVR1_recall$accRecall,
                                             dataSchemaVR2_recall$accRecall,
                                             dataSchemaVR3_recall$accRecall,
                                             dataSchemaVR4_recall$accRecall),
                               euclideanDist = c(dataSchemaVR1_recall$euclideanDist,
                                                 dataSchemaVR2_recall$euclideanDist,
                                                 dataSchemaVR3_recall$euclideanDist,
                                                 dataSchemaVR4_recall$euclideanDist))

combinedData_recall$Exp    <- combinedData_recall$objLocTargetRating 
combinedData_recall$subNum <- as.character(combinedData_recall$subNum)

# Scaling based on Gelman et al. (2008) and https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations
# Mean = 0 and SD = 0.5
combinedData_recall$s_x <- (combinedData_recall$Exp - mean(combinedData_recall$Exp ))/(sd(combinedData_recall$Exp)/0.5)
```

```{r pooled_recall_analysis}
pooled_recall <- glmer(accRecall ~  s_x + I(s_x*s_x) 
                     + (1 | subNum)
                     + (1 | objNum), 
                    data = combinedData_recall, 
                    family = binomial, 
                    control = glmerControl(optimizer = "bobyqa"),
                    nAGQ = 1)

pooled_recall_tab <- createResultTable(pooled_recall)
```

```{r pooled_euclidDistance_analysis}
pooled_euclidDistance <- glmer(euclideanDist ~  s_x + I(s_x*s_x) 
                     + (1 | subNum)
                     + (1 | objNum), 
                     family = Gamma,
                     data = combinedData_recall)

pooled_euclidDistance_tab <- createResultTable(pooled_euclidDistance)
```

```{r pooled_recollection}
# Combine data to one data frame
combinedData_remember <- data.frame(Experiment = c(rep('2', length(dataSchemaVR2$subNum)),
                                                   rep('3a', length(dataSchemaVR3$subNum)),
                                                   rep('3b', length(dataSchemaVR4$subNum))),
                               set        = c(rep('2', length(dataSchemaVR2$subNum)),
                                              as.character(dataSchemaVR3$setNum),
                                              as.character(dataSchemaVR4$setNum)),
                               subNum = c(as.character(dataSchemaVR2$subNum),
                                          as.character(dataSchemaVR3$subNum),
                                          as.character(dataSchemaVR4$subNum)),
                               objNum = c(dataSchemaVR2$objNum,
                                          dataSchemaVR3$objNum,
                                          dataSchemaVR4$objNum),
                               objLocTargetRating = c(dataSchemaVR2$objLocTargetRating,
                                                      dataSchemaVR3$objLocTargetRating,
                                                      dataSchemaVR4$objLocTargetRating),
                               resCon = c(as.integer(as.character(dataSchemaVR2$resCon)),
                                          as.integer(as.character(dataSchemaVR3$resCon)),
                                          as.integer(as.character(dataSchemaVR4$resCon))))


# Creating new labels
remembered <- rep(0, dim(combinedData_remember)[1])
remembered[combinedData_remember$resCon == 1] <- 1
combinedData_remember$remembered <- remembered

# Exclude no-memory (i.e. hasn't seen object) 
combinedData_remember <- combinedData_remember[combinedData_remember$resCon != 0, ]


# Scaling based on Gelman et al. (2008) and https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations
# Mean = 0 and SD = 0.5
combinedData_remember$Exp  <- combinedData_remember$objLocTargetRating 
combinedData_remember$s_x <- (combinedData_remember$Exp - mean(combinedData_remember$Exp ))/(sd(combinedData_remember$Exp)/0.5)
```

```{r pooled_recollection_analysis}
pooled_recollection <- glmer(remembered ~  s_x + I(s_x*s_x) 
                             + (1 | subNum)
                             + (1 | objNum), 
                            data = combinedData_remember, 
                            family = binomial, 
                            control = glmerControl(optimizer = "bobyqa"),
                            nAGQ = 1)

pooled_recollection_tab <- createResultTable(pooled_recollection)
```

```{r pooled_recollection_exclusive}
# Creating new labels
remembered <- rep(0, dim(combinedData_remember)[1])
remembered[combinedData_remember$resCon == 1] <- 1
remembered[combinedData_remember$resCon == 2] <- NA_integer_ # Exclude familiar trials 
combinedData_remember$remembered <- remembered

# Exclude no-memory (i.e. hasn't seen object) 
combinedData_remember <- combinedData_remember[combinedData_remember$resCon != 0, ]


# Scaling based on Gelman et al. (2008) and https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations
# Mean = 0 and SD = 0.5
combinedData_remember$Exp  <- combinedData_remember$objLocTargetRating 
combinedData_remember$s_x <- (combinedData_remember$Exp - mean(combinedData_remember$Exp ))/(sd(combinedData_remember$Exp)/0.5)
```

```{r pooled_recollection_exclusive_analysis}
pooled_recollection_exclusive <- glmer(remembered ~  s_x + I(s_x*s_x) 
                             + (1 | subNum)
                             + (1 | objNum), 
                            data = combinedData_remember, 
                            family = binomial, 
                            control = glmerControl(optimizer = "bobyqa"),
                            nAGQ = 1)

pooled_recollection_exclusive_tab <- createResultTable(pooled_recollection_exclusive)
```

```{r pooled_familiar_ind}
# Combine data to one data frame
combinedData_familiar_ind <- data.frame(Experiment = c(rep('2', length(dataSchemaVR2$subNum)),
                                                       rep('3a', length(dataSchemaVR3$subNum)),
                                                       rep('3b', length(dataSchemaVR4$subNum))),
                               set        = c(rep('2', length(dataSchemaVR2$subNum)),
                                              as.character(dataSchemaVR3$setNum),
                                              as.character(dataSchemaVR4$setNum)),
                               subNum = c(as.character(dataSchemaVR2$subNum),
                                          as.character(dataSchemaVR3$subNum),
                                          as.character(dataSchemaVR4$subNum)),
                               objNum = c(dataSchemaVR2$objNum,
                                          dataSchemaVR3$objNum,
                                          dataSchemaVR4$objNum),
                               objLocTargetRating = c(dataSchemaVR2$objLocTargetRating,
                                                      dataSchemaVR3$objLocTargetRating,
                                                      dataSchemaVR4$objLocTargetRating),
                               resCon = c(as.integer(as.character(dataSchemaVR2$resCon)),
                                          as.integer(as.character(dataSchemaVR3$resCon)),
                                          as.integer(as.character(dataSchemaVR4$resCon))))


# Creating new labels
# Coding familiar judgements as independent
familiar_ind <- rep(0, dim(combinedData_familiar_ind)[1])
familiar_ind[combinedData_familiar_ind$resCon == 1] <- NA_integer_
familiar_ind[dataSchemaVR4$resCon == 2] <- 1
combinedData_familiar_ind$familiar_ind <- familiar_ind

# Exclude no-memory (i.e. hasn't seen object) 
combinedData_familiar_ind <- combinedData_familiar_ind[combinedData_familiar_ind$resCon != 0, ]
# Scaling based on Gelman et al. (2008) and https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations
# Mean = 0 and SD = 0.5
combinedData_familiar_ind$Exp  <- combinedData_familiar_ind$objLocTargetRating 
combinedData_familiar_ind$s_x <- (combinedData_familiar_ind$Exp - mean(combinedData_familiar_ind$Exp ))/(sd(combinedData_familiar_ind$Exp)/0.5)

```

```{r pooled_familiar_ind_anlaysis}
pooled_familiar_ind <- glmer(familiar_ind ~  s_x + I(s_x*s_x) 
                             + (1 | subNum)
                             + (1 | objNum), 
                            data = combinedData_familiar_ind, 
                            family = binomial, 
                            control = glmerControl(optimizer = "bobyqa"),
                            nAGQ = 1)

pooled_familiar_ind_tab <- createResultTable(pooled_familiar_ind)
```

```{r pooled_familiar_red}
# Combine data to one data frame
combinedData_familiar_red <- data.frame(Experiment = c(rep('2', length(dataSchemaVR2$subNum)),
                                                       rep('3a', length(dataSchemaVR3$subNum)),
                                                       rep('3b', length(dataSchemaVR4$subNum))),
                                        set        = c(rep('2', length(dataSchemaVR2$subNum)),
                                                       as.character(dataSchemaVR3$setNum),
                                                       as.character(dataSchemaVR4$setNum)),
                                        subNum = c(as.character(dataSchemaVR2$subNum),
                                                   as.character(dataSchemaVR3$subNum),
                                                   as.character(dataSchemaVR4$subNum)),
                                        objNum = c(dataSchemaVR2$objNum,
                                                   dataSchemaVR3$objNum,
                                                   dataSchemaVR4$objNum),
                                        objLocTargetRating = c(dataSchemaVR2$objLocTargetRating,
                                                               dataSchemaVR3$objLocTargetRating,
                                                               dataSchemaVR4$objLocTargetRating),
                                        resCon = c(as.integer(as.character(dataSchemaVR2$resCon)),
                                                   as.integer(as.character(dataSchemaVR3$resCon)),
                                                   as.integer(as.character(dataSchemaVR4$resCon))))


# Creating new labels
# Coding familiar judgements as redundant
familiar_red <- rep(0, dim(combinedData_familiar_red)[1])
familiar_red[combinedData_familiar_red$resCon == 1] <- 1
familiar_red[combinedData_familiar_red$resCon == 2] <- 1
combinedData_familiar_red$familiar_red <- familiar_red

# Exclude no-memory (i.e. hasn't seen object) 
combinedData_familiar_red <- combinedData_familiar_red[combinedData_familiar_red$resCon != 0, ]
# Scaling based on Gelman et al. (2008) and https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations
# Mean = 0 and SD = 0.5
combinedData_familiar_red$Exp  <- combinedData_familiar_red$objLocTargetRating 
combinedData_familiar_red$s_x <- (combinedData_familiar_red$Exp - mean(combinedData_familiar_red$Exp ))/(sd(combinedData_familiar_red$Exp)/0.5)
```

```{r pooled_familiar_red_anlaysis}
pooled_familiar_red <- glmer(familiar_red ~  s_x + I(s_x*s_x) 
                             + (1 | subNum)
                             + (1 | objNum), 
                            data = combinedData_familiar_red, 
                            family = binomial, 
                            control = glmerControl(optimizer = "bobyqa"),
                            nAGQ = 1)

pooled_familiar_red_tab <- createResultTable(pooled_familiar_red)
```

```{r pooled_recall_normative}
normativeData <- read.table("D:/Alex/Laptop/Desktop/schemaVR/schemaVR3/data/normativeData.txt", 
                            header = TRUE, 
                            sep = "\t")

normativeData$objectNames <- as.character(normativeData$objectNames)
dataSchemaVR1$objNam      <- as.character(dataSchemaVR1$objNam)
dataSchemaVR2$objName     <- as.character(dataSchemaVR2$objNam)
dataSchemaVR3$objNam      <- as.character(dataSchemaVR3$objNam)
dataSchemaVR4$objNam      <- as.character(dataSchemaVR4$objNam)
normativeData$objectNames[normativeData$objectNames == 'fruit bowl'] <- 'bowl of fruits'


# Getting normative expectancy for target
dataSchemaVR1$objLocTargetNorm  <- NA
dataSchemaVR1$generalRatingNorm <- NA
# Add normative location rating
for(i in 1:dim(dataSchemaVR1)[1]){
  dataSchemaVR1$objLocTargetNorm[i] <- normativeData[normativeData$objectNames == as.character(dataSchemaVR1$objName[i]), 
                                                     paste("loc", dataSchemaVR1$targetLocation[i], sep = "")]
  dataSchemaVR1$generalRatingNorm[i] <- normativeData[normativeData$objectNames == as.character(dataSchemaVR1$objName[i]), 
                                                     'general']
}

# Getting normative expectancy for target
dataSchemaVR2$objLocTargetNorm  <- NA
dataSchemaVR2$generalRatingNorm <- NA
# Add normative location rating
for(i in 1:dim(dataSchemaVR2)[1]){
  dataSchemaVR2$objLocTargetNorm[i] <- normativeData[normativeData$objectNames == as.character(dataSchemaVR2$objName[i]), 
                                                     paste("loc", dataSchemaVR2$targetLocation[i], sep = "")]
  dataSchemaVR2$generalRatingNorm[i] <- normativeData[normativeData$objectNames == as.character(dataSchemaVR2$objName[i]), 
                                                     'general']
}

# Getting normative expectancy for target
dataSchemaVR3$objLocTargetNorm  <- NA
dataSchemaVR3$generalRatingNorm <- NA
# Add normative location rating
for(i in 1:dim(dataSchemaVR3)[1]){
  dataSchemaVR3$objLocTargetNorm[i] <- normativeData[normativeData$objectNames == as.character(dataSchemaVR3$objNam[i]), 
                                                     paste("loc", dataSchemaVR3$targetLocation[i], sep = "")]
  dataSchemaVR3$generalRatingNorm[i] <- normativeData[normativeData$objectNames == as.character(dataSchemaVR3$objNam[i]), 
                                                     'general']
}

# Getting normative expectancy for target
dataSchemaVR4$objLocTargetNorm  <- NA
dataSchemaVR4$generalRatingNorm <- NA
# Add normative location rating
for(i in 1:dim(dataSchemaVR4)[1]){
  dataSchemaVR4$objLocTargetNorm[i] <- normativeData[normativeData$objectNames == as.character(dataSchemaVR4$objNam[i]), 
                                                     paste("loc", dataSchemaVR4$targetLocation[i], sep = "")]
  dataSchemaVR4$generalRatingNorm[i] <- normativeData[normativeData$objectNames == as.character(dataSchemaVR4$objNam[i]), 
                                                     'general']
}

# Re creating recall DF because there was an error in the code
dataSchemaVR1_recall <- subset(dataSchemaVR1, dataSchemaVR1$recallNoMemory == 0 | is.na(dataSchemaVR1$recallNoMemory))
dataSchemaVR2_recall <- subset(dataSchemaVR2, dataSchemaVR2$recallMemory != 0 | is.na(dataSchemaVR2$recallMemory))
dataSchemaVR3_recall <- subset(dataSchemaVR3, dataSchemaVR3$recallMemory != 0 | is.na(dataSchemaVR3$recallMemory))
dataSchemaVR4_recall <- subset(dataSchemaVR4, dataSchemaVR4$recallMemory != 0 | is.na(dataSchemaVR4$recallMemory))

#### Combine data to one data frame
combinedData_recall <- data.frame(Experiment = c(rep('1', length(dataSchemaVR1_recall$subNum)),
                                              rep('2', length(dataSchemaVR2_recall$subNum)),
                                              rep('3a', length(dataSchemaVR3_recall$subNum)),
                                              rep('3b', length(dataSchemaVR4_recall$subNum))),
                               set        = c(rep('1', length(dataSchemaVR1_recall$subNum)),
                                              rep('2', length(dataSchemaVR2_recall$subNum)),
                                              as.character(dataSchemaVR3_recall$setNum),
                                              as.character(dataSchemaVR4_recall$setNum)),
                               subNum = c(as.character(dataSchemaVR1_recall$subNum),
                                          as.character(dataSchemaVR2_recall$subNum),
                                          as.character(dataSchemaVR3_recall$subNum),
                                          as.character(dataSchemaVR4_recall$subNum)),
                               objNum = c(dataSchemaVR1_recall$objNum,
                                          dataSchemaVR2_recall$objNum,
                                          dataSchemaVR3_recall$objNum,
                                          dataSchemaVR4_recall$objNum),
                               objLocTargetRating = c(dataSchemaVR1_recall$objLocTargetRating,
                                                      dataSchemaVR2_recall$objLocTargetRating,
                                                      dataSchemaVR3_recall$objLocTargetRating,
                                                      dataSchemaVR4_recall$objLocTargetRating),
                               accRecall = c(dataSchemaVR1_recall$accRecall,
                                             dataSchemaVR2_recall$accRecall,
                                             dataSchemaVR3_recall$accRecall,
                                             dataSchemaVR4_recall$accRecall),
                               euclideanDist = c(dataSchemaVR1_recall$euclideanDist,
                                                 dataSchemaVR2_recall$euclideanDist,
                                                 dataSchemaVR3_recall$euclideanDist,
                                                 dataSchemaVR4_recall$euclideanDist),
                               objLocTargetNorm = c(dataSchemaVR1_recall$objLocTargetNorm,
                                                    dataSchemaVR2_recall$objLocTargetNorm,
                                                    dataSchemaVR3_recall$objLocTargetNorm,
                                                    dataSchemaVR4_recall$objLocTargetNorm),
                               generalRatingNorm = c(dataSchemaVR1_recall$generalRatingNorm,
                                                    dataSchemaVR2_recall$generalRatingNorm,
                                                    dataSchemaVR3_recall$generalRatingNorm,
                                                    dataSchemaVR4_recall$generalRatingNorm))

combinedData_recall$subNum <- as.factor(combinedData_recall$subNum)
combinedData_recall$objLocTargetNorm <- (combinedData_recall$objLocTargetNorm - mean(combinedData_recall$objLocTargetNorm ))/(sd(combinedData_recall$objLocTargetNorm)/0.5)
combinedData_recall$generalRatingNorm <- (combinedData_recall$generalRatingNorm - mean(combinedData_recall$generalRatingNorm ))/(sd(combinedData_recall$generalRatingNorm)/0.5)

pooled_norm_recall <- glmer(accRecall ~  objLocTargetNorm + 
                  I(objLocTargetNorm*objLocTargetNorm) + # generalRatingNorm+
                  (1 | subNum) + (1 | objNum), data = combinedData_recall, 
                family = binomial, 
                control = glmerControl(optimizer = "bobyqa"),
                nAGQ = 1)

pooled_norm_recall_tap <- createResultTable(pooled_norm_recall)
```

```{r corr_between_rating, eval = FALSE}
cor.test(combinedData_AFC$objLocTargetRating, combinedData_AFC$objLocTargetNorm)


ggplot(combinedData_AFC, aes(objLocTargetRating, objLocTargetNorm)) + 
  geom_point() +
  geom_smooth(method = 'loess', colour = 'red') +
  geom_smooth(method = 'lm', colour = 'blue') +
  labs(title = 'Correlation between normative and individual ratings',
       x = "Participants' rartings",
       y = 'Normative ratings')
```

```{r pooled_AFC_normative}
# Re creating recall DF because there was an error in the code
dataSchemaVR1_AFC    <- subset(dataSchemaVR1, dataSchemaVR1$resCon != 1)
dataSchemaVR2_AFC    <- subset(dataSchemaVR2, dataSchemaVR2$resCon != 0)
dataSchemaVR3_AFC    <- subset(dataSchemaVR3, dataSchemaVR3$resCon != 0)
dataSchemaVR4_AFC    <- subset(dataSchemaVR4, dataSchemaVR4$resCon != 0)

#### Combine data to one data frame
combinedData_AFC <- data.frame(Experiment = c(rep('1', length(dataSchemaVR1_AFC$subNum)),
                                              rep('2', length(dataSchemaVR2_AFC$subNum)),
                                              rep('3a', length(dataSchemaVR3_AFC$subNum)),
                                              rep('3b', length(dataSchemaVR4_AFC$subNum))),
                               set        = c(rep('1', length(dataSchemaVR1_AFC$subNum)),
                                              rep('2', length(dataSchemaVR2_AFC$subNum)),
                                              as.character(dataSchemaVR3_AFC$setNum),
                                              as.character(dataSchemaVR4_AFC$setNum)),
                               subNum = c(as.character(dataSchemaVR1_AFC$subNum),
                                          as.character(dataSchemaVR2_AFC$subNum),
                                          as.character(dataSchemaVR3_AFC$subNum),
                                          as.character(dataSchemaVR4_AFC$subNum)),
                               objNum = c(dataSchemaVR1_AFC$objNum,
                                          dataSchemaVR2_AFC$objNum,
                                          dataSchemaVR3_AFC$objNum,
                                          dataSchemaVR4_AFC$objNum),
                               objLocTargetRating = c(dataSchemaVR1_AFC$objLocTargetRating,
                                                      dataSchemaVR2_AFC$objLocTargetRating,
                                                      dataSchemaVR3_AFC$objLocTargetRating,
                                                      dataSchemaVR4_AFC$objLocTargetRating),
                               accAFC = c(dataSchemaVR1_AFC$accAFC,
                                          dataSchemaVR2_AFC$accAFC,
                                          dataSchemaVR3_AFC$accAFC,
                                          dataSchemaVR4_AFC$accAFC),
                               objLocTargetNorm = c(dataSchemaVR1_AFC$objLocTargetNorm,
                                                    dataSchemaVR2_AFC$objLocTargetNorm,
                                                    dataSchemaVR3_AFC$objLocTargetNorm,
                                                    dataSchemaVR4_AFC$objLocTargetNorm),
                               generalRatingNorm = c(dataSchemaVR1_AFC$generalRatingNorm,
                                                     dataSchemaVR2_AFC$generalRatingNorm,
                                                     dataSchemaVR3_AFC$generalRatingNorm,
                                                     dataSchemaVR4_AFC$generalRatingNorm))

combinedData_AFC$subNum <- as.factor(combinedData_AFC$subNum)
combinedData_AFC$objLocTargetNorm <- (combinedData_AFC$objLocTargetNorm - mean(combinedData_AFC$objLocTargetNorm ))/(sd(combinedData_AFC$objLocTargetNorm)/0.5)
combinedData_AFC$generalRatingNorm <- (combinedData_AFC$generalRatingNorm - mean(combinedData_AFC$generalRatingNorm ))/(sd(combinedData_AFC$generalRatingNorm)/0.5)

pooled_norm_AFC <- glmer(accAFC ~  objLocTargetNorm + 
                  I(objLocTargetNorm*objLocTargetNorm) +# generalRatingNorm+
                  (1 | subNum) + (1 | objNum), data = combinedData_AFC, 
                family = binomial, 
                control = glmerControl(optimizer = "bobyqa"),
                nAGQ = 1)

pooled_norm_AFC_tap <- createResultTable(pooled_norm_AFC)

# plot(combinedData_AFC$)
```

```{r pooled_analyis_result_table}
pooled_recall_tab$measure <- 'recall'
pooled_euclidDistance_tab$measure <- 'euclidDistance'
pooled_3AFC_tab$measure <- '3AFC'
pooled_recollection_tab$measure <- 'recollection'
pooled_recollection_exclusive_tab$measure <- 'recollection (exclusivity)'
pooled_familiar_ind_tab$measure <- 'familiarity (independence)'
pooled_familiar_red_tab$measure <- 'familiarity (redundancy)'

pooled_analysis <- rbind(pooled_recall_tab, pooled_euclidDistance_tab, pooled_3AFC_tab, 
                        pooled_recollection_tab, pooled_recollection_exclusive_tab,
                        pooled_familiar_ind_tab, pooled_familiar_red_tab)

kable(pooled_analysis)
```