---
title: "Results section 4"
author: "Joern Alexander Quent"
date: "28/05/2021"
output: html_document
---

```{r setup, include=FALSE}
# Libraries
library(assortedRFunctions) # install via devtools::install_github("JAQuent/assortedRFunctions")
library(knitr)
library(ggplot2)
library(brms)
library(plyr)
library(lmerTest)
library(MRColour)
library(BayesFactor)
library(cowplot)
library(polspline)
library(gridExtra)
library(grid)

# Options
options(scipen=999)
opts_knit$set(eval.after = 'fig.cap')
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, include = TRUE)

######################################################
# Path to parent folder schemaVR
path2parent <- "D:/Alex/Laptop/Desktop/schemaVR" # This need to be changed to run this document
######################################################
```


# 3AFC
```{r AFC1}
# Load data
load(paste0(path2parent, "/schemaVR4/analysis/schemaVR_all_AFC_zeroPrior_set_20210728_120702.RData"))

# Get model comparison BFs
bayes_factor(model_schemaVR_all_AFC_set1, model_schemaVR_all_AFC_set2)
bayes_factor(model_schemaVR_all_AFC_no_set, model_schemaVR_all_AFC_set1)
```

```{r AFC2}
fixef_temp <- fixef(model_schemaVR_all_AFC_no_set)
report1    <- brms_fixef_report(fixef_temp[2,], 3)
report2    <- brms_fixef_report(fixef_temp[3,], 3)

# Linear
postDist        <- posterior_samples(model_schemaVR_all_AFC_no_set)$b_sExp
areaPrior       <- NA # doesn't matter
priorDensity    <- dstudent_t(0 , 7, 0, 1)
bf_AFC_lin      <- signif(savage_dickey_ratio(postDist, priorDensity, areaPrior, 'two.sided'), 3)

# Quadratic term
postDist        <- posterior_samples(model_schemaVR_all_AFC_no_set)$b_IsExpMUsExp
areaPrior       <- 0.5 # because it's symmetrical 
priorDensity    <- dstudent_t(0 , 7, 0, 1)
bf_AFC_quad     <- signif(savage_dickey_ratio(postDist, priorDensity, areaPrior, 'two.sided'), 3)
```

Linear `r report1`. BF10 = `r bf_AFC_lin` 

Quadratic `r report2`. BF10 = `r bf_AFC_quad`

# Recall
```{r recall1}
# Load data
load(paste0(path2parent, "/schemaVR4/analysis/schemaVR_all_recall_zeroPrior_set_20210728_122921.RData"))

# Get model comparison BFs
bayes_factor(model_schemaVR_all_recall_set1, model_schemaVR_all_recall_set2)
bayes_factor(model_schemaVR_all_recall_no_set, model_schemaVR_all_recall_set1)
```

```{r recall2}
fixef_temp <- fixef(model_schemaVR_all_recall_no_set)
report1    <- brms_fixef_report(fixef_temp[2,], 3)
report2    <- brms_fixef_report(fixef_temp[3,], 3)

# Linear
postDist        <- posterior_samples(model_schemaVR_all_recall_no_set)$b_sExp
areaPrior       <- NA # doesn't matter
priorDensity    <- dstudent_t(0 , 7, 0, 1)
bf_recall_lin      <- signif(savage_dickey_ratio(postDist, priorDensity, areaPrior, 'two.sided'), 3)

# Quadratic term
postDist        <- posterior_samples(model_schemaVR_all_recall_no_set)$b_IsExpMUsExp
areaPrior       <- 0.5 # because it's symmetrical 
priorDensity    <- dstudent_t(0 , 7, 0, 1)
bf_recall_quad     <- signif(savage_dickey_ratio(postDist, priorDensity, areaPrior, 'two.sided'), 3)
```

Linear `r report1`. BF10 = `r bf_recall_lin` 

Quadratic `r report2`. BF10 = `r bf_recall_quad`

# Recollection
```{r recollection1}
# Load data
load(paste0(path2parent, "/schemaVR4/analysis/schemaVR_all_recollection_zeroPrior_set_20210728_131252.RData"))

# Get model comparison BFs
bayes_factor(model_schemaVR_all_rem_set1, model_schemaVR_all_rem_set2)
bayes_factor(model_schemaVR_all_rem_no_set, model_schemaVR_all_rem_set1)
```

```{r recollection2}
fixef_temp <- fixef(model_schemaVR_all_rem_no_set)
report1    <- brms_fixef_report(fixef_temp[2,], 3)
report2    <- brms_fixef_report(fixef_temp[3,], 3)

# Linear
postDist        <- posterior_samples(model_schemaVR_all_rem_no_set)$b_sExp
areaPrior       <- NA # doesn't matter
priorDensity    <- dstudent_t(0 , 7, 0, 1)
bf_rem_lin      <- signif(savage_dickey_ratio(postDist, priorDensity, areaPrior, 'two.sided'), 3)

# Quadratic term
postDist        <- posterior_samples(model_schemaVR_all_rem_no_set)$b_IsExpMUsExp
areaPrior       <- 0.5 # because it's symmetrical 
priorDensity    <- dstudent_t(0 , 7, 0, 1)
bf_rem_quad     <- signif(savage_dickey_ratio(postDist, priorDensity, areaPrior, 'two.sided'), 3)
```

Linear `r report1`. BF10 = `r bf_rem_lin` 

Quadratic `r report2`. BF10 = `r bf_rem_quad`