---
title: "Results section 5"
author: "Joern Alexander Quent"
date: "11/08/2021"
output: html_document
---

```{r setup, include=FALSE}
# Libraries
library(assortedRFunctions) # install via devtools::install_github("JAQuent/assortedRFunctions")
library(knitr)
library(ggplot2)
library(brms)
library(plyr)
library(lmerTest)
library(MRColour)
library(BayesFactor)
library(cowplot)
library(polspline)
library(gridExtra)
library(grid)

# Options
options(scipen=999)
opts_knit$set(eval.after = 'fig.cap')
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, include = TRUE)

######################################################
# Path to parent folder schemaVR
path2parent <- "D:/Alex/Laptop/Desktop/schemaVR" # This need to be changed to run this document
######################################################
```


# High confidence
```{r AFC1}
# Load data
load(paste0(path2parent, "/schemaVR1/analysis/schemaVR1_highConf_20210806_180741.RData"))
```

```{r AFC2}
fixef_temp <- fixef(model_schemaVR1_highConf)
report1    <- brms_fixef_report(fixef_temp[2,], 3)
report2    <- brms_fixef_report(fixef_temp[3,], 3)

# Linear
postDist        <- posterior_samples(model_schemaVR1_highConf)$b_sExp
areaPrior       <- NA # doesn't matter
priorDensity    <- dstudent_t(0 , 7, 0, 1)
bf_AFC_lin      <- signif(savage_dickey_ratio(postDist, priorDensity, areaPrior, 'two.sided'), 3)

# Quadratic term
postDist        <- posterior_samples(model_schemaVR1_highConf)$b_IsExpMUsExp
areaPrior       <- 0.5 # because it's symmetrical 
priorDensity    <- dstudent_t(0 , 7, 0, 1)
bf_AFC_quad     <- signif(savage_dickey_ratio(postDist, priorDensity, areaPrior, 'two.sided'), 3)
```

Linear `r report1`. BF10 = `r bf_AFC_lin` 

Quadratic `r report2`. BF10 = `r bf_AFC_quad`
